# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 495)
        font = QtGui.QFont()
        font.setPointSize(9)
        Form.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 771, 341))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.horizontalLayoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.colorView = QtWidgets.QGraphicsView(self.splitter)
        self.colorView.setObjectName("colorView")
        self.dephView = QtWidgets.QGraphicsView(self.splitter)
        self.dephView.setObjectName("dephView")
        self.horizontalLayout.addWidget(self.splitter)
        self.timeSlider = QtWidgets.QSlider(Form)
        self.timeSlider.setGeometry(QtCore.QRect(20, 460, 771, 22))
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.loadButton = QtWidgets.QPushButton(Form)
        self.loadButton.setGeometry(QtCore.QRect(20, 10, 131, 41))
        self.loadButton.setObjectName("loadButton")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(20, 410, 771, 41))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.previousFrameButton = QtWidgets.QPushButton(self.splitter_2)
        self.previousFrameButton.setObjectName("previousFrameButton")
        self.playButton = QtWidgets.QPushButton(self.splitter_2)
        self.playButton.setObjectName("playButton")
        self.nextFrameButton = QtWidgets.QPushButton(self.splitter_2)
        self.nextFrameButton.setObjectName("nextFrameButton")
        self.videoInformation = QtWidgets.QTextBrowser(Form)
        self.videoInformation.setGeometry(QtCore.QRect(160, 10, 631, 41))
        self.videoInformation.setStyleSheet("")
        self.videoInformation.setObjectName("videoInformation")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loadButton.setText(_translate("Form", "Load"))
        self.previousFrameButton.setText(_translate("Form", "Previous frame"))
        self.playButton.setText(_translate("Form", "Play"))
        self.nextFrameButton.setText(_translate("Form", "Next frame"))
